name: cloud_kitchen
description: A new Flutter project.



version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  geolocator: ^7.0.0
  google_maps_flutter: ^2.0.11
  firebase_core: ^1.7.0
  firebase_auth: ^3.1.3
  firebase_analytics: ^8.3.3
  cloud_firestore: ^2.5.3
  provider: ^6.0.1
  get: ^4.3.8
  shared_preferences: ^2.0.0-nullsafety
  pin_code_fields: ^7.3.0
  path_provider: ^2.0.0
  expand_widget: ^2.1.0
  carousel_slider: ^4.0.0
  mask_text_input_formatter: ^2.0.0-nullsafety.2
  cupertino_icons: ^1.0.2
  flutter_slidable: ^0.6.0
  share_plus: ^3.0.2
  flutter:
    sdk: flutter

flutter_icons:
  image_path: "assets/food/logo.png"
  android: "launcher_icon"
  ios: true
  
dev_dependencies:  
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/font/Gilroy-Extrabold.ttf
        - asset: assets/font/Gilroy-Regular.ttf

  uses-material-design: true
  assets:
    - assets/logo/
    - assets/food/

